### ISSUE TITLE
Docker container build environment and better dependency management

### ISSUE THREAD

**Issue by BentouDev** [BentouDev/YAGE#36]
Create and setup appveyor to use windows docker image with prebuild dependencies

**Comment by MrJaqbq** [comment]
Related to #31

**Comment by lukasz-pyrzyk** [comment]
:beer:

**Comment by MrJaqbq** [comment]
Investigate usage of custom repository [conan.io](http://conan.io) with prebuild dependency binaries. Host additional CI on AppVeyor and Travis (docker based) which builds and uploads those dependencies.

**Comment by lukasz-pyrzyk** [comment]
:o
